platform :ios, '10.0'

target 'UnitTestProject' do
  use_frameworks!
  pod 'SwiftyGif'

  target 'UnitTestProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnitTestProjectUITests' do
    # Pods for testing
  end

end
